{{- if eq (include "adp.needInitContainer" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "adp.fullname" . }}-pod-reader-binding
  labels:
    {{- include "adp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "adp.fullname" . }}-pod-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "adp.fullname" . }}-sa
    namespace: {{ .Release.Namespace }}
{{- end }}
