apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "adp.fullname" . }}-pod-reader
  labels:
    {{- include "adp.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
