apiVersion: v1
kind: Service
metadata:
  name: {{ include "adp.fullname" . }}
  labels:
    {{- include "adp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "adp.selectorLabels" . | nindent 4 }}