apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "job-env.fullname" . }}-cluster-role
  labels:
    {{- include "job-env.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "{{ .Values.rbac.hookWeight }}"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  # 读取节点信息（检测节点 label）
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  # 创建和更新 ConfigMap
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "patch"]
