apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "job-env.fullname" . }}-sa
  labels:
    {{- include "job-env.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "{{ .Values.rbac.hookWeight }}"
    "helm.sh/hook-delete-policy": before-hook-creation
