tad:
  type: helm
  images:
    adp-app-config:
      url: lmbke.tencentcloudcr.com/llm_customer/app-config:46_2512091122_master_private_906a551e_private
  instanceStrategy:
    level: region
  labels: {}
  namespace: customer
  product: llm-knowledge-engine
  registries:
    images: registry.tce.com
    packages: http://registry.tce.com:1181
  services: {}
image: lmbke.tencentcloudcr.com/llm_customer/app-config:46_2512091122_master_private_906a551e_private
replicas: 1
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi
appName: app-config
app_config:
  knowledge_qa_model:
    intent_recognize_model_name: workflow-pro # 知识库问答意图识别默认兜底模型名称
    text2sql_model_name: nl2sql-16b # 知识库问答文本转sql默认兜底模型名称，非信创nl2sql-16b，信创 nl2sql